channels:
  global:
    id: -1 # Set to -1, comment out, or remove to disable channel bridge
    switch-message: '<gray>You are now in <color><channel> <gray>chat!'
    toggle-on-message: '<gray>You can now see <color><channel> <gray>chat!'
    toggle-off-message: '<gray>You can no longer see <color><channel> <gray>chat!'
    formats:
      discord-to-mc: '<gray>[<blue>Discord<gray>] <username>: <white><message>' # Placeholders: username, displayname, channel, server, message, primaryrole
      staff: '<gray>{[%deluxetags_tag%<gray>]} %player_displayname% <gray>» <white><message>'
      default: '<gray>[%deluxetags_tag%<gray>] %player_displayname%<gray>: <white><message>'
    webhook: 'URL_HERE' # Comment out / remove to disable webhook
    color: WHITE # Removing this option defaults to 'WHITE'
    default: true # Removing this option defaults to 'false'
    ignorable: true # Removing this option defaults to 'true'
    distance: -1 # Set to -1, comment out, or remove to disable distance checking

bot-token: -1

language:
  ignoring-user: '<green>You are now ignoring <gold><player><green>!'
  not-ignoring-user: '<greey>You are no longer ignoring <gold><player><green>!'