caps-protection:
  enabled: true
  minimum-length: 10
  percent-caps: 80
  block-message: false

filters:
  enabled: true
  # The keys ("****" for example) are what the text is replaced with
  # The strings in the lists ("lag" etc) are what's replaced
  filters:
    # In this example, any instance of "lag" or "laggggg" will be replaced with "****"
    "****":
      - "lag"
      - "la[g]+"
    "":
      - "broccoli sucks"
  # Anything in blocked-words will prevent the message from being sent at all.
  blocked-words:
    - "pineapple doesn't belong on pizza"
  channels:
    - '*' # Use '*' to mean all channels

clear-chat:
  # The message sent to clear chat, you probably want to leave this blank
  message: ""
  # How many messages will be sent in order to clear chat
  message-count: 100

language:
  is-now-shadow-muted: '<yellow>Player <player> is now shadow muted!'
  no-longer-shadow-muted: '<yellow>Player <player> is no longer shadow muted!'
  shadow-mute-exempt: '<red>Player <player> is exempt from being shadow muted!'
  is-now-muted: '<yellow>Player <player> is now muted!'
  no-longer-muted: '<yellow>Player <player> is no longer muted!'
  mute-exempt: '<red>Player <player> is exempt from being muted!'
  reloaded: '<yellow>ChatModeration config has been reloaded!'
  clear-notify: '<yellow>Chat has been cleared by <player>.'
  clear-exempt: '<yellow>You were exempt from the clear due to your permissions!'
